# Traefik configuration
api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

providers:
  consul:
    endpoints:
      - 'consul:8500'
    prefix: 'traefik'
    watch: true

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO

accessLog:
  format: json
